version: "3.7"

networks:
  default:
    external:
      name: home_service
      # driver: bridge

  # default:
  #   name: home_service
  #   driver: host

services:
  portaineragent:
    image: portainer/agent
    ports:
      - ${PORTAINERAGENT_PORT_9001}:9001
    container_name: portaineragent
    environment:
      - CAP_HOST_MANAGEMENT=1
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${BASE_LOGGING_MAXFILE}
        max-size: ${BASE_LOGGING_MAXSIZE}
    restart: ${BASE_RESTART_STRATEGY}
    volumes:
      - /:/host
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

  portainer:
    image: portainer/portainer-ce
    ports:
      - ${PORTAINER_PORT_9000}:9000
    command: -H unix:///var/run/docker.sock
    container_name: portainer
    environment:
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${BASE_LOGGING_MAXFILE}
        max-size: ${BASE_LOGGING_MAXSIZE}
    restart: ${BASE_RESTART_STRATEGY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${BASE_DATA_DIR}/portainer:/data
      - ${HOME_SCRIPT_STORAGE}:/storage

  rclone_mount:
    image: hereisderek/rclone_mergerfs_mounter:latest
    container_name: rclone_mount
    privileged: true
    security_opt:
      - seccomp:unconfined
    devices:
      - /dev/fuse:/dev/fuse
    ports:
      - ${RCLONE_MOUNT_PORT_5572}:5572
    cap_add:
      - SYS_ADMIN
      - SETPCAP
      - MKNOD
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - RC_USER=${RC_USER}
      - RC_PASS=${RC_PASS}
      - USE_RCD=false
      - PARAMS_COMMON_EXTRA=-vv
      - RCLONE_REMOTE=${RCLONE_MOUNT_SHARE}
      - MERGERFS_MOUNT_RCLONE_PATH=${RCLONE_MOUNT_MERGERFS_MOUNT_RCLONE_PATH:-"/"}
      - RCLONE_CONFIG_FILE_NAME=${RCLONE_CONFIG_FILE_NAME:-rclone.conf}
      - RC_SERVE=true 
      - RC_ENABLE_METRICS=true
      # - RCLONE_IP_PORT=:5572

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${RCLONE_MOUNT_SHARE_CONFIG_FOLDER}:/config/rclone
      - ${BASE_CACHE_DIR}/rclone_mount:/cache
      - ${RCLONE_MOUNT_MERGERFS_LOCAL}:/storage
      - ${MOUNT_PARENT}:/mnt:shared
    



  sonarr:
    image: lscr.io/linuxserver/sonarr
    ports:
      - ${SONARR_PORT_8989}:8989
    container_name: sonarr
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${BASE_LOGGING_MAXFILE}
        max-size: ${BASE_LOGGING_MAXSIZE}
    restart: ${BASE_RESTART_STRATEGY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DATA_DIR}/sonarr:/config
      - ${HOME_SCRIPT_STORAGE}:/storage
      
  radarr:
    image: lscr.io/linuxserver/radarr
    ports:
      - ${RADARR_PORT_7878}:7878
    container_name: radarr
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${BASE_LOGGING_MAXFILE}
        max-size: ${BASE_LOGGING_MAXSIZE}
    restart: ${BASE_RESTART_STRATEGY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DATA_DIR}/radarr:/config
      - ${HOME_SCRIPT_STORAGE}:/storage
  
  bazarr:
    image: lscr.io/linuxserver/bazarr
    ports:
      - ${BAZARR_PORT_6767}:6767
    container_name: bazarr
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${BASE_LOGGING_MAXFILE}
        max-size: ${BASE_LOGGING_MAXSIZE}
    restart: ${BASE_RESTART_STRATEGY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DATA_DIR}/bazarr:/config
      - ${HOME_SCRIPT_STORAGE}:/storage

  lidarr:
    image: lscr.io/linuxserver/lidarr
    ports:
      - ${LIDARR_PORT_8686}:8686
    container_name: lidarr
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${BASE_LOGGING_MAXFILE}
        max-size: ${BASE_LOGGING_MAXSIZE}
    restart: ${BASE_RESTART_STRATEGY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DATA_DIR}/lidarr:/config
      - ${HOME_SCRIPT_STORAGE}:/storage

  readarr:
    image: hotio/readarr:nightly
    # image: ghcr.io/linuxserver/readarr
    container_name: readarr
    ports:
      - ${READARR_PORT_8686}:8787
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${BASE_LOGGING_MAXFILE}
        max-size: ${BASE_LOGGING_MAXSIZE}
    restart: ${BASE_RESTART_STRATEGY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DATA_DIR}/lidarr:/config
      - ${HOME_SCRIPT_STORAGE}:/storage

  prowlarr:
    image: linuxserver/prowlarr:nightly
    container_name: prowlarr
    ports:
      - ${PROWLARR_PORT_8787}:8787
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={TZ}
    logging:
      driver: json-file
      options:
        max-file: ${BASE_LOGGING_MAXFILE}
        max-size: ${BASE_LOGGING_MAXSIZE}
    restart: ${BASE_RESTART_STRATEGY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DATA_DIR}/prowlarr:/config
      - ${HOME_SCRIPT_STORAGE}:/storage

  jackett:
    image: lscr.io/linuxserver/jackett
    ports:
      - ${JACKETT_PORT_9117}:9117
    container_name: jackett
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - AUTO_UPDATE=true
    logging:
      driver: json-file
      options:
        max-file: ${BASE_LOGGING_MAXFILE}
        max-size: ${BASE_LOGGING_MAXSIZE}
    restart: ${BASE_RESTART_STRATEGY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DATA_DIR}/jackett:/config
      - ${HOME_SCRIPT_STORAGE}/_downloads/jackett:/downloads


  qbittorrent:
    container_name: qbittorrent
    image: hotio/qbittorrent
    # networks:
    #   - compose_default
    ports:
      - ${QBIT_MANAGE_PORT_8080}:8080
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${BASE_LOGGING_MAXFILE}
        max-size: ${BASE_LOGGING_MAXSIZE}
    restart: ${BASE_RESTART_STRATEGY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DATA_DIR}/qbittorrent:/config
      - ${HOME_SCRIPT_STORAGE}:/storage



  jellyfin:
    image: lscr.io/linuxserver/jellyfin:nightly
    container_name: jellyfin
    runtime: nvidia
    # privileged: true
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - JELLYFIN_PublishedServerUrl=192.168.50.12 #optional
    volumes:
      - ${BASE_DATA_DIR}/jellyfin:/config
      - ${JELLYFIN_CACHE_DIR}:/config/cache
      - ${JELLYFIN_METADATA_DIR}:/config/data/metadata
      - ${JELLYFIN_TRANSCODE_DIR}:/config/data/transcodes
      - ${HOME_SCRIPT_STORAGE}:/storage
    restart: ${BASE_RESTART_STRATEGY}  
    ports:
      - ${JELLYFIN_WEB_8096}:8096
      # - 8920:8920 #optional
      - ${JELLYFIN_PORT_7359}:7359/udp #optional
      - ${JELLYFIN_PORT_1900}:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidia1:/dev/nvidia1
      - /dev/nvidia2:/dev/nvidia2
      - dev/nvidiactl:dev/nvidiactl
      - dev/nvidia-uvm:dev/nvidia-uvm
      - dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]


  # nzbget:
  #   image: lscr.io/linuxserver/nzbget
  #   ports:
  #     - ${NZBGET_PORT_6789}:6789
  #   container_name: nzbget
  #   environment:
  #     - PGID=${PGID}
  #     - PUID=${PUID}
  #     - TZ=${TZ}
  #   logging:
  #     driver: json-file
  #     options:
  #       max-file: ${BASE_LOGGING_MAXFILE}
  #       max-size: ${BASE_LOGGING_MAXSIZE}
  #   restart: ${NZBGET_RESTART}
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - ${BASE_DATA_DIR}/nzbget:/config
  #     - ${HOME_SCRIPT_STORAGE}:/storage

  transmission:
    image: lscr.io/linuxserver/transmission
    ports:
      - ${TRANSMISSION_PORT_51413}:51413
      - ${TRANSMISSION_PORT_51413}:51413/udp
      - ${TRANSMISSION_PORT_6881}:6881
      - ${TRANSMISSION_PORT_6881}:6881/udp
      - ${TRANSMISSION_PORT_9091}:9091
    container_name: transmission
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${BASE_LOGGING_MAXFILE}
        max-size: ${BASE_LOGGING_MAXSIZE}
    restart: ${BASE_RESTART_STRATEGY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DATA_DIR}/transmission:/config
      - ${HOME_SCRIPT_STORAGE}:/storage